server {
    if ($host = cvetik.analystexe.ru) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name cvetik.analystexe.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/cvetik.analystexe.ru;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/cvetik-box/cvetik-box.sock;
    }
}

server {
    listen 443 ssl;
    server_name cvetik.analystexe.ru;

    ssl_certificate /etc/letsencrypt/live/cvetik.analystexe.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cvetik.analystexe.ru/privkey.pem;

    client_max_body_size 10m;

    location = /metrics {
        allow 127.0.0.1;
        deny all;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/cvetik-box/cvetik-box.sock;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/cvetik-box/cvetik-box.sock;
    }
}
